name: reachable URL test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  URL_TO_TEST: "https://latessa.github.iy"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          pip install requests

      - name: Test URL
        run: |
          python3 ${GITHUB_WORKSPACE}/tests/val.py $URL_TO_TEST
